# ITI5196 Assessment 2 Task2
#### Student Name: Eddy
#### Student ID: 33495068

Date: 13/11/2023

Version: 1.0

Environment: Python 3.10.11 and Jupyter notebook extension in VS code

Libraries used: please include the main libraries you used in your assignment here, e.g.,:
* pandas 
* re 
* numpy
* math
* mathplotlib.pyplot
* datetime
* collections
* difflib



<span style="color: red"> Note that this is a sample notebook only. You will need to fill in the proper markdown and code blocks. You might also want to make necessary changes to the structure to meet your own needs. It is important to make sure the logic of how you finish the assessment is clearly shown in this notebook! </span>

# Import Libraries

In [1]:
import pandas as pd
import math
import re
import numpy as np
import matplotlib.pyplot as plt

## Task 2. Integration

In this task, you are given a 2nd job advertisement dataset dataset2.csv. You will then integrate this dataset with the output from Task 1 (dataset1_solution.csv) and resolve any schema level and data level conflicts. 

<span style="color: red"> You might have complex notebook structure in this section, please feel free to create your own notebook structure. </span>

First we read both the dataset that's been wrangled and the second dataset

In [2]:
#Loading both dataset
dataset1 = pd.read_csv("dataset1_solution.csv")
dataset2 = pd.read_csv("dataset2.csv")

Next we EDA the second dataset first to get a feel of the dataset

In [3]:
#EDAing the second dataset
dataset2.info()
dataset2.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Job Title         334 non-null    object
 1   Organisation      334 non-null    object
 2   Location          334 non-null    object
 3   Category          334 non-null    object
 4   Salary per month  334 non-null    int64
 5   Fraction          3 non-null      object
 6   Contract Type     327 non-null    object
 7   Views             334 non-null    float64
 8   OpeningDate       334 non-null    object
 9   OpeningTime       334 non-null    object
 10  ClosingDate       334 non-null    object
 11  ClosingTime       334 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 31.4+ KB

(334, 12)

In [4]:
#Showing the first 10 of second dataset
dataset2.head(10)

,Job Title,Organisation,Location,Category,Salary per month,Fraction,Contract Type,Views,OpeningDate,OpeningTime,ClosingDate,ClosingTime
0,Aviation loans administration,cer Financial,London,Finance and Accounting,2800,NaN,Contract,26899.161398,2013-10-06,00:00:00,2013-12-05,00:00:00
1,"Payroll Analyst City upto **** , ****",LMA Recruitment Ltd,London,Finance and Accounting,2917,NaN,Permanent,27998.181788,2012-10-03,12:00:00,2012-11-02,12:00:00
2,Investment Team Assistant for leading Private ...,Austin Andrew Ltd,London,Finance and Accounting,3750,NaN,Permanent,35955.060147,2012-01-01,00:00:00,2012-01-31,00:00:00
3,SWAPS COLLATERAL CONTROL OFFICER,Brian Durham Recruitment Services Limited,City,Finance and Accounting,3333,NaN,Permanent,31983.941441,2012-10-14,00:00:00,2012-11-13,00:00:00
4,Loans Administration Temp,cer Financial,London,Finance and Accounting,3280,NaN,Contract,31487.694078,2012-11-17,12:00:00,2013-01-16,12:00:00
5,Oversight and Compliance Manager Global Custo...,Citifocus Limited,The City,Finance and Accounting,3750,NaN,Permanent,36032.076862,2012-11-01,12:00:00,2012-12-31,12:00:00
6,ALM Actuary,Reed Insurance,South East England,Finance and Accounting,6250,NaN,Permanent,59953.789569,2012-03-22,00:00:00,2012-04-21,00:00:00
7,SUPPORT ANALYST Front Office,Newside Consulting Limited,London,Finance and Accounting,4667,NaN,Permanent,44848.708848,2013-03-09,12:00:00,2013-05-08,12:00:00
8,Forex Sales Manager,LMA Recruitment Ltd,London,Finance and Accounting,4583,NaN,Permanent,44035.320755,2013-11-26,12:00:00,2013-12-26,12:00:00
9,Management Accountant Commodity Trading,LMA Recruitment Ltd,London,Finance and Accounting,4792,NaN,Permanent,46031.453138,2013-06-21,15:00:00,2013-09-19,15:00:00

From looking at the dataset it's clear that this dataset doesn't match the schema that were given in the global schema. Therefore, we will look at each column problem and fix it from there. First off the missing Id column.

# Id

As mentioned before, the column Id is missing. From the global schema, the Id column is 8 digit id of the job advertisement. From what was observed in the first dataset. They are all unique therefore they can serve as the Primary Key for both dataset. Because of that, when making the Id column for this dataset it's also must be a unique 8 digit dataset. To make sure it's unique, we check the maximum number from the first dataset then increase it incrementaly for the 2nd dataset

In [5]:
#Code to show the maximum id for dataset 1
max(dataset1['Id'])

72705504

As we can see the max Id is 72705504 so we increase it from there for dataset2

In [6]:
#Code to insert the id column increasing from 72705505. And to make sure the name match the global schema Id
dataset2.insert(0, 'Id', range(72705505, 72705505 + len(dataset2)))

Next is the Job Title Column

# Job Title

First we skim the column with for loop

In [7]:
#Skimming the column
for x,y in dataset2['Job Title'].value_counts().to_dict().items():
    print(x,y)

Aviation loans administration 1
Lease Accountant 1
Assistant Assurance Manager 1
Cost Accountant  Supply Chain Finance 1
Rent Accountant / Property Accountant 1
Product Support Analyst 1
OTC Client Services 1
PPI Quality Assurer 1
Senior Financial Accountant Insurance 1
IRD and Commodities Confirmations Specialists 1
Credit Risk Reporting Manager / Assistant Manager 1
Snr Relationship Executive  Fund Management  Fluent German 1
Business Analyst  BAU and Change 1
Business Analyst  OTC Pricing 1
Compliance Associate 1
Credit Risk Senior Analyst 1
Property Finance Manager 1
Leading Gloabl Consultancy  Capital Markets Consultants 1
Impairment and Capital Manager 1
Internal Auditor and Senior Auditor 1
KYC Remediation 1
Sales Administrator/ Client Service Associate 1
Financial Crime Analyst (Compliance) 1
Associate Director Product and Support  (Cash Management) 1
IFRS Accountant 1
Operational Due Diligence (ODD) Analyst 1
Physical Oil Settlements (Pricing ) Manager 1
Legal Compliance Regulatory Change Analyst 1
Senior Manager, Credit Risk ( Workouts) 1
ITALIAN  Broker Support 1
Non Marine Broker Backup / Technician  Commercial Account Handler 1
Junior Database Developer 1
Consultant  Executive Search (Recruitment)  Banking  Mayfair 1
Buy Side Sales Support  EMEA  London 1
Audit Senior  Top 20 firm 1
Senior Complaints Handler 1
PROPERTY FINANCE SUPPORT 1
Quality and Risk Advisor 1
Compliance Monitoring Adviser 1
UK Direct Business Manager (Part time) 1
Internal Audit Manager and Senior Manager 1
IT Permanent Recruitment  Researcher / Trainee Consultant 1
Senior Operational Risk Analyst (AVP) 1
Business Development Manager  Asset Finance  NW England 1
Trade Structured Finance Manager  Commodity Trader 1
Sales Consultant  Birmingham  Up to **** , ****  Bonus 1
Sales Support Coordinator (Financial Services) 1
Junior Ruby Developer / Tester 1
Executive Assistant to Head of Global Investment company 1
Senior PA / Secretary  (GERMAN SPEAKER) 1
Internal Auditor  Part qualified  Insurance 1
Assistant Accountant  Interim 1
Snr Trade and Commodity Finance Support 1
Assistant Billing Manager  Chelmsford 1
Corporate Account Executive  East Midlands 1
Analyst  Tax Operations 1
Senior Associate Internal Audit (Mandarin speaking) 1
Credit Risk Analyst  Counterparty Risk 1
Corporate Treasury Assistant Manager 1
Customer Insight and Value Data Analyst 1
Senior Payments Solutions Manager 1
Senior Manager  AML and Client Relationship 1
FSA / BANK OF ENGLAND REPORTING OFFICER 1
Private Client Investment 1
Payroll / HR Officer 1
Executive Assistant with Sage 200 1
Claims Assistant 1
MOTOR CLAIMS PROFESSIONALS REQUIRED 1
Equity Settlements Dividends Processing 1
Trainee Recruitment Consultant  Engineering IT 1
Finance Analyst  Equities 1
Reinsurance Accounts Manager / Leader 1
Service Manager Corporate Banking 1
Information Security Consultants / Managers 1
Assistant Manager  Operations Fund Oversight 1
KYC Remediation Analyst 1
Advanced Data Analytic Managers 1
Senior Grade Trader 1
Loans Closer 1
Information Security Manager  Financial Services / Public Sect 1
Loans and Payments Supervisor 1
Graduate trainee with intern exp 1
MANAGERS SENIOR MANAGERS 1
Compliance Risk Manager  (Property Finance) 1
Payroll Analyst  City upto **** , **** 1
Risk Manager  Consumer Credit 1
Head of Finance  Insurance 1
Assistant Accountant  Financial Services 1
Technology Sales Executive  Superb Opportunity 1
Equities Fixed Income Trade Support 1
Credit Analyst  Oil Trading 1
Shipping Aviation Portfolio Manager 1
Hedge Fund Trade Support and NAV 1
IT Sourcing Manager (Hardware) 1
Senior Manager, Operational Risk (612 month contract) 1
Origination  Syndication Loan Sales 1
Fund Data Manager  Marketing 1
Project Managers  Insurance 1
Senior Data Specialist: Sovereign Research and Ratings to **** , **** 1
Banking Customer Services Payments Clerk 1
MOTOR CLAIMS TEAM LEADER / MANAGER 1
Assistant Accountant  ACCA / CIMA studier 1
MOTOR CLAIMS COMPLAINTS TEAM LEADER 1
Business Development Manager  Fluent Chinese 1
physical commodities 1
Personal Injury Claims Negotiator  Basingstoke 1
Internal audit manager  Change 1
Relationship / Sales executive  Multilingual 1
Risk Manager  FSA / Regulatory Frameworks 1
Management Accountant  London 1
Financial Control Officer  Regulatory Reporting 1
Newly Qualified Associate 1
Loans Analyst 1
SENIOR BUSINESS BANKING RELATIONSHIP MANAGER  EXCELLENT OPPORTUNITY 1
Covered Bonds Credit Analyst 1
Capital Markets Management Accountant 1
Consultant  Credit Risk 1
Senior Expenses Manager 1
Finance Compliance Director 1
Manager  Senior Manager, Regulatory Risk Consulting 1
Mergers Acquisitions Senior Manager Financial Services London 1
SENIOR PENSIONS / CLIENT SERVICES ASSOCIATE  DC (LONDON OUTSKIRTS) 1
Senior FX Dealer with client base 1
Treasury Accounting and Operations Manager 1
Compliants Investigator 1
Modelling AnalystLloyds Underwriting (quantitative Ist degree) 1
Trade Finance Collateral Management 1
Stop commuting and work locally 1
Junior Analyst Developer (NET, C) 1
Work local  Stop commuting 1
Senior Credit Manager  Asset Finance 1
Quantitative Analytics Manager 1
Associate, Transaction Management 1
Senior European Fund Accountant  Real Estate 1
Product Control (CFO), Structured Equities, Associate / AVP 1
Operations Systems Manager 1
Stress Testing Modeller 1
Equity Fund Research Analyst 1
Head of Business Modelling and Analysis 1
Change Management Business Analyst 1
Shipping Officer 1
Credit Assistant Manager  Property Division 1
FINANCIAL PLANNING CONSULTANT  PRIVATE CLIENTS 1
Retail Management Accountant 1
Client Reporting Executive 1
Senior Development Underwriter 1
Trade Finance Officer  French Speaker 1
Compliance Analyst  Financial Promotions 1
Financial Accountant Film Media Company Supply Chain Team 1
Corporate Action Administrator 1
TECHNICAL TRAINER  MOTOR CLAIMS  KENT 1
Media Communications Asset Management 1
Cash Manager 1
Associate Director  Planning Group 1
Financial Planner  Milton Keynes 1
VP Senior Operations 1
Commodities Credit Officer, AVP 1
Commodity Broker  Diamond / Metals 1
Internal Audit, Commodities, Investment Banking London 1
Global Head of Compliance / Director / London 1
Collections Analyst 1
MOTOR CLAIMS HANDLER  PERSONAL INJURY EXPERIENCE 1
MORTGAGE ADVISOR  LEADING IFA FIRM 1
PQ Management Accountant (**** month FTC) 1
Banking Operations Officer 1
Sales Account Management Support 1
Mobile Solutions Delivery Manager 1
Cash Originator 1
Deputy Chief Executive 1
CREDIT ANALYST  up to ****k  London 1
Treasury Risk Controller : Middle Office Compliance : Oil Gas Co 1
Senior Audit Investigations Manager 1
Portfolio Finance Planning Manager 1
Banking Cashier 1
Equity Research Sales  Private Clients 1
Middle Office Support 1
Settlements Adminstrator  Investment Management 1
Billing Coordinator 1
Treasury Dealer FX Dealer 1
Assistant Accountant  Business Partnering 1
Senior Equity Settlements 1
RFP Writer 1
Management Support Executive 1
Fund Accountant  Hedge Fund 1
Operations Analyst 1
Shares and Market Options Sales Consultant 1
Compliance Assistant 1
Business Change Analyst / Project Manager 1
Assistant Vice President  Auditor 1
DO YOU HAVE 2 YEARS CURRENT BUY SIDE OPERATIONS EXPERIENCE? 1
Senior Business Analyst / Business Analyst  Claims 1
Senior HR Consultant 1
Investment Manager 1
KYC Remediation Analyst AML, JMLSG, OnBoarding 1
Business Change Senior Project Manager  East Midlands 1
Chartered IFA Farnham Up to **** , **** (********k OTE) 1
Real Estate Finance  Asset Management Analyst 1
Management Account 1
SECONDARY LOANS / SYNDICATIONS ADMIN / SETTLEMENTS 1
PMO / Senior PMO Analyst 1
Mortgage Protection AdvisorEstate Agent 1
Sourcing Manager  Professional Fees 1
Operational Risk and Control Manager 1
International Communications Manager 1
Royalties Manager / FP A Manager 1
Committee Secretary  London  ****k 1
Insurance  Financial Accountant 1
Business Strategy Analyst 1
Trade Compliance Analyst 1
Regulatory Accountant 1
Head of Underwriting Development  Life 1
Transaction Reporting Specialist 1
Regulatory control change project manager 1
Cashier  Fluent Mandarin 1
Cheque Processing Clerk 1
Internal Resourcing Coordinator 1
Accounts Receivable / Sales ledger Assistant 1
Sales Support Executive 1
Credit Trade Finance Manager 1
Compliance Monitoring Asset Management London 1
CFD Sales Trader 1
Management Accountant  Commodity Trading 1
Forex Sales Manager 1
SUPPORT ANALYST  Front Office 1
ALM Actuary 1
Oversight and Compliance Manager  Global Custody Operations 1
Loans Administration  Temp 1
SWAPS COLLATERAL CONTROL OFFICER 1
Investment Team Assistant for leading Private Equity firm 1
VP, Regulatory Risk 1
Compliance Monitoring Manager  Banking 1
Loans Documentation Analyst 1
Model Validation Quantitative Analyst 1
Voluntary Corporate Actions 1
Fund Accountant  London 1
Oversight and Compliance Manager 1
Transactional Management Team Leader 1
Ops Process Management Analyst 1
Project Manager  Private Client 1
Risk Controller 1
Portfolio / Performance Analyst 1
Product Control Analyst  Oil 1
Senior Accountant  Group Reporting 1
Business Analyst  Change 1
Business Partner  Treasury 1
Trade Control VP 1
Financial Controller / Group Accountant 1
Middle Office Analyst FTC 1
Risk Review Compliance Officer 1
VP Operational Risk 1
Fixed Income Trade Support  Investment Management 1
Corporate Retail Banking PMO (Perm) 1
Fluent German Speaker : Compliance Position 1
MANDARIN SPEAKING INTERNAL AUDITOR 1
Company Secretary / Administrator 1
Trade Finance Officer 1
Credit Analyst FI Banks 1
PPI Head of Group Customer Relations 1
Sales Operations Director 1
Client Relationship Executive Supervisor 1
Credit Risk Stratergy  Manager 1
Senior Corporate Underwriter 1
**** x Digital Channel Optimisation Specialists 1
Business Intelligence / Data Analytic Managers 1
Data Analyst (SAS / SQL) 1
Senior Business Modelling Analyst  AVP 1
Legal Entity Controller 1
Implementation Consultant / Business Analyst  F / S Software 1
Risk Analytics and Credit Model Development (Retail) 1
Compliance Consultant Opportunities 1
Senior Compliance Associate 1
FX DEALER (CORPORATE CLIENTS) 1
Client Reporting Analyst 1
Fraud Intelligence Analyst 1
Risk Analyst  Insurance  sixmonth contract 1
Commercial Finance Associate 1
Senior Business Analyst  Investment Operations Systems 1
IT Audit  Tier One Banking Group 1
Internal Audit, VP, Investment Banking, Quantitative 1
Senior Audit Manager  Market Model Risk 1
Global MI Analytics Business Manager  Leading Investment Bank 1
TRAINEE COMMERCIAL INSURANCE ACCOUNT HANDLER 1
Paraplanner Fareham Circa **** , ****  Benefits 1
Analyst  MI 1
Accounts Payable / Compliance / Administrator 1
Consultant  Currency sales 1
Senior Fund Administrator 1
Credit Assistant 1
Business Development Sales Executive x **** 1
Paraplanner Hampshire Up to **** , **** 1
Temp Hybrid Transfer Agency / Treasury / Cash Flow for Master Feeder 1
Corporate Development Executive  Birmingham 1
Trading Support Engineer (FIX) 1
Institutional Client Sales Associate 1
Head of Loans Administration 1
Governance, Risk Compliance Manager 1
Decision Science Manager  Cards  Awesome Opportunity  South East 1
Insurance Internal Audit 1
Senior Internal Audit Manager  Change 1
Interim Syndicate Accountant 1
Treasury Operations 1
Insurance Technician 1
Collateral Analyst 1
Banking Cashier / Customer Services Clerk 1
Graduate Scheme  Asset Management 1
Secretary / Team Support  International Banking 1
Finance Secretary / PA 1
Banking Administrator 1
Management Information Analyst  Insurance experience essential 1
Assistant Accountant Financial Services Experience Required 1
Investment Operations Reconciliations Administrator  Parttime 1
Investment Operations Transfer Administrator 1
Accounts Assistant  Asset Management 1
ETF Sales UK Institutional clients 1
Internal Auditor, Capital Markets 1
Lending Manager / Senior Manager, Commercial Real Estate Workout 1
Casualty Claims Handler 1
Sales Trader 1
Compliance Analyst/ Specialist 1
Compliance Supervisor 1
Group Head of IT Security 1
IT Risk / Audit  Senior Manager 1
Vice President  Banking Regulatory Review Challenge 1
Trade Finance Analyst 1
Credit Analyst (Aircraft Finance) 1
Credit Supervision, Credit Sanctioning 1
Client Relationship Manager  Asset Management 1
COMPLIANCE MONITORING OFFICER 1
Compliance Manager : IFA Funds 1
Risk Liquidity Analyst 1
Treasury Supervisor CLS 1
Senior Accountant (Insurance) 1
Corporate Credit Analyst 1
Corporate Tax Compliance Client Service Administrator 1

The most obvious mistake is that the column names didn't match the global schema. The data are also not yet normalized therefore we normalize the data according to what has been done in task 1 and change the column name

In [8]:
#Change the column name from job title to Title
dataset2 = dataset2.rename(columns={'Job Title': 'Title'})

#Normalize the data like in dataset1

#Creating a function to normalize the title column
def normalizetitle(title):
    # normalize to upper case letters
    title = title.upper()
    # change AND to &
    title = title.replace(" AND ", " & ")
    # replace multiple spaces with a single space, also trim spaces on both side
    title = re.sub( '\s+', ' ', title).strip()
    return title

#Applying the function to the column
dataset2['Title'] = dataset2.Title.apply(lambda x: normalizetitle(x))

We're done with Title column, next Organisation column

# Organisation

First we skim the column with for loop

In [9]:
#Skimming the column
for x,y in dataset2['Organisation'].value_counts().to_dict().items():
    print(x,y)

LMA Recruitment Ltd 19
Oliver James Associates Limited 15
Brian Durham Recruitment Services Limited 12
Ambition Europe Limited 12
cer Financial 11
Morgan McKinley Group Limited 11
Kennedy Pearce Consulting Ltd 10
Goodman Masson Recruitment Services Ltd 10
Randstad Financial Professional Ltd 10
Badenoch Clark Ltd 9
Hays Financial Markets 9
Prime Personnel Services Ltd 9
Idex Consulting LLP 8
The Oakland Partnership Limited 8
Black Swan Associates Limited 8
Clark James Ltd 7
Twenty Recruitment Ltd 7
C.K.R. Recruitment Limited 7
Incite Solutions Ltd 6
Austin Andrew Ltd 6
Reed Finance 6
Austin Benn 6
Argyll Scott International Limited 5
Alexander Lloyd 4
Venn Group Limited 4
Mayford James Limited 4
Montpellier Resourcing Ltd 3
Livingston Edwards Ltd 3
James Associates Recruitment Ltd 3
Employment Specialists Ltd 3
Insight Recruitment Solutions Ltd 3
Bruin Financial Limited 3
Walker Hamill Ltd 3
Marks Sattin  Ltd 3
Maldon Partners Ltd 3
Harrison Holgate 3
Monument Financial Recruitment Ltd 2
Blayney Personnel Limited 2
Balanced People Limited 2
Campbell James Limited 2
Experis Limited 2
Concilium Finance Limited 2
Paritas Recruitment Limited 2
MW Recruitment Ltd 2
Taylor James Resourcing Limited 2
Albany Beck Consulting Ltd 2
Saul Partners 2
Eximius Operations Ltd 2
MDM Consultants Limited 2
Insight Professional Solutions Ltd 2
Next Employment Limited 2
Citifocus Limited 2
The Ocean Partnership Limited 2
Carnegie Consulting Ltd 1
Selby Jennings Ltd 1
Arthur Financial Ltd 1
Rees Draper Wright Ltd 1
Plumstead Bond Limited 1
City East Recruitment Limited 1
Momenta Group Limited 1
Reed Purchasing 1
Newedge 1
Colyer Dodd and Company Limited 1
Matador Recruitment 1
MW Appointments Ltd 1
Brightpool 1
Newside Consulting Limited 1
Reed Insurance 1
IPS Group Ltd 1
JHA Recruitment Consultancy 1
Hewitson Walker 1
PBR Construction LTD 1
Generation Resourcing Limited 1
TalentFlow Ltd 1
ASK Recruitment 1
Jigsaw Recruiting Ltd 1
MCGREGOR BOYALL ASSOCIATES LIMITED 1
EDIT Professional Ltd 1
Rebecca Poulter Recruitment 1
Apache Associates Ltd 1
Wavelength Recruitment 1
Robert Half 1
Daniel Recruitment Ltd 1
PeopleGenius Ltd 1
Brooker Associates Limited 1
Dante Recruitment Ltd 1
REC Solutions Ltd 1
Hill Newton Recruitment Limited 1
Eaglecliff Limited 1
Charles Levick Limited 1
Lesley Ray 1
Astbury Marsden Partners Ltd 1
Sublime Resourcing Limited 1
People First Recruitment Limited 1
Sharon Gay Associates Limited 1
Procura Ltd 1
High Finance Group 1
Capco 1
Cahill Personnel Ltd 1
Jefferson Tiley Ltd 1

Again the most obvious problem is the column names didn't match the global schema. There's also some inconsistency and upper and lower cases problem. Therefore we change the column name and normalize the data like in task 1

In [10]:
#Change the column name from job title to Title
dataset2 = dataset2.rename(columns={'Organisation': 'Company'})

#Normalize the data like in dataset1

# the following function is the clean and normalize the company field.
def normalizecompany(company):
    if pd.isnull(company):
        return company
    else:
        # normalize to upper case letters
        company = company.upper()
        # replace multiple spaces with a single space, also trim spaces on both side
        company = re.sub( '\s+', ' ', company).strip()
        # remove special character at the end
        company = re.sub(r"\W+$", "", company)
        # replace LIMITED with LTD
        company = company.replace("LIMITED", "LTD")
        # replace " AND " with " & " for processing 
        company = company.replace(" & ", " AND ")
        # remove all special characters except space and dot
        company = re.sub(r'([^\w\s\.]|_)', '', company)
        # change " AND " back to " & " 
        company = company.replace(" AND ", " & ")
        return company

#Applying the function to the column
dataset2['Company'] = dataset2.Company.apply(lambda x: normalizecompany(x))

Organisation column is done, next is location

# Location

First we skim the column with for loop

In [11]:
#Skimming the column
for x,y in dataset2['Location'].value_counts().to_dict().items():
    print(x,y)

London 158
The City 92
UK 25
City 13
South East England 5
West End 5
South West London 3
Central London 3
Crawley 2
Hertfordshire 2
Birmingham 2
Croydon 2
East Midlands 1
Reading 1
North London 1
Guildford 1
West Sussex 1
South East London 1
Basingstoke 1
Buckinghamshire 1
Southampton 1
Peterborough 1
Bristol 1
North West England 1
Farnham 1
West London 1
Chelmsford 1
Fareham 1
Hampshire 1
Berkshire 1
Redhill 1
Dorking 1
Cheltenham 1
Bath 1

Doesn't look like there's obvious mistake with the column. So we just normalize the column and move on

In [12]:
#Defining function to normalize the location by uppercasing the location and deleting spaces + trailing spaces

def normalizelocation(location):
        #We know that location column doesn't have missing values do no need to deal with values
        # normalize to upper case letters
        location = location.upper()
        # replace multiple spaces with a single space, also trim spaces on both side
        return location
dataset2['Location'] = dataset2.Location.apply(lambda x: normalizelocation(x))

Next is category

# Category

First we skim the column with for loop

In [13]:
#Skimming the column
for x,y in dataset2['Category'].value_counts().to_dict().items():
    print(x,y)

Finance and Accounting 319
Information Technology 12
PR, Advertising and Marketing 3

First, the column name already match the global schema. However, the data didn't match what has been cleaned in dataset 1 therefore it is normalized and matched to the dataset 1

In [14]:
#Defining function to normalize the category by uppercasing the category and deleting spaces + trailing spaces

def normalizecategory(category):
    #function to skip null is not needed because we known there's no null in this column    
    # normalize to upper case letters        
    category = category.upper()
    # replace " AND " with " & "
    category = category.replace(" AND ", " & ")
    return category

#Applying the function
dataset2['Category'] = dataset2.Category.apply(lambda x: normalizecategory(x))

#Code to correct the incorrect category names by replacing it with the correct names

dataset2.Category.replace({'FINANCE & ACCOUNTING': 'ACCOUNTING & FINANCE JOBS','INFORMATION TECHNOLOGY': 'IT JOBS',
                          'PR, ADVERTISING & MARKETING': 'PR, ADVERTISING & MARKETING JOBS'}, inplace=True)

Next is the Salary per month Column

# Salary Per Month

First we skim the column with for loop

In [15]:
#Skimming the column
for x,y in dataset2['Salary per month'].value_counts().to_dict().items():
    print(x,y)

3333 19
3750 18
4583 15
4167 14
3958 13
3125 12
3542 12
5000 11
4375 11
2917 11
5417 10
6250 10
5833 9
2500 9
2292 8
2083 7
4792 7
5208 6
2708 6
7500 6
7083 5
1875 5
6667 4
3167 4
2375 4
4000 4
2000 4
5625 3
2333 3
2800 3
5500 3
2667 3
2417 3
7917 3
1667 3
2250 2
3000 2
3833 2
6042 2
1750 2
2208 2
4708 2
2625 2
3208 2
4667 2
6400 2
3458 2
1708 1
1792 1
5750 1
4200 1
3417 1
1458 1
1625 1
3200 1
2583 1
1250 1
3060 1
3280 1
2167 1
4480 1
3583 1
5958 1
6458 1
5542 1
3250 1
1520 1
2833 1
3021 1
4292 1
1167 1
3760 1
2146 1
2125 1
3500 1
1417 1
2400 1
3800 1
4500 1
6700 1
6500 1
2880 1
1500 1
3520 1
6875 1
1583 1
3600 1
3440 1
1560 1

It's clear that there are problems with this column. First the name didn't match the global schema. Second the salary is in month format when it should be in Annual format which menas it should be / year so both problems are fixed. Also from the EDA at the start, the data format is integer when it should be float so it's also fixed.

In [16]:
#Change the column name from Salary per month to Salary
dataset2 = dataset2.rename(columns={'Salary per month': 'Salary'})

#Changing the Salary from per month to per year and coverting it to float
dataset2['Salary'] = dataset2.Salary.apply(lambda x: float(x * 12))

Next is Fraction column

# Fraction

First we skim the column with for loop

In [17]:
#Skimming the column
for x,y in dataset2['Fraction'].value_counts().to_dict().items():
    print(x,y)

Part Time 3

From the global schema, there's no column named fraction but looking at the code output. It seems that this column should be ContractType column. Also from the EDA earlier and the output of the code. It's clear that there are missing data in the column. As with task 1, the NA values is changed to non_specified

In [18]:
#Renaming the column name to ContractType
dataset2 = dataset2.rename(columns={'Fraction': 'ContractType'})

#Renaming the data to the correct values
dataset2.ContractType.replace('Part Time', 'part_time', inplace=True)
dataset2.ContractType.fillna('non-specified', inplace=True)

Next is Contract Type

# Contract Type

First we skim the column with for loop

In [19]:
#Skimming the column
for x,y in dataset2['Contract Type'].value_counts().to_dict().items():
    print(x,y)

Permanent 272
Contract 55

From the output, it seems this column should be ContractTime column in the global schema. From the EDA earlier we also know that there are missing data in this column, so those missing datas are replaced with non_specified according to the global schema

In [20]:
#Renaming the column name to ContractType
dataset2 = dataset2.rename(columns={'Contract Type': 'ContractTime'})

#Renaming the data to the correct values
dataset2.ContractTime.replace('Permanent', 'permanent', inplace=True)
dataset2.ContractTime.replace('Contract', 'contract', inplace=True)
dataset2.ContractTime.fillna('non-specified', inplace=True)

Next is the Views column

# Views

First we skim the column with for loop

In [21]:
#Skimming the column
for x,y in dataset2['Views'].value_counts().to_dict().items():
    print(x,y)

26899.161397970605 1
34007.41425216036 1
32004.213169285074 1
32810.31319769833 1
36039.74406175828 1
36027.62141528344 1
38001.10418790716 1
40344.636603278544 1
39983.05847559989 1
37967.76076561211 1
40025.07772236232 1
42041.20743707225 1
47972.54467749888 1
51984.167476841685 1
53956.96161184573 1
47989.05455043044 1
51959.76603535924 1
45212.29328021178 1
55204.07194244721 1
32037.13195359884 1
38437.20450959419 1
16810.384167167067 1
27990.19624434398 1
21983.72566644667 1
41959.82348739989 1
37962.57503727589 1
47977.78433261791 1
52797.17945846199 1
76049.59185261675 1
15563.021488916258 1
21561.473589353387 1
22361.472779541404 1
23956.584412251315 1
23972.547816552888 1
22827.084355378287 1
25979.712139727617 1
14025.204735254758 1
28012.42844325566 1
25651.81493778961 1
31984.803110371373 1
55975.82372712514 1
17187.64362867477 1
36005.75781681212 1
34029.464470547144 1
58040.01847403868 1
12000.821499404925 1
19158.725338249973 1
19979.926577643 1
27222.04941244969 1
30441.56872706853 1
30445.63265705156 1
33038.70582459982 1
31985.551189232687 1
29959.583978617826 1
31989.03221604988 1
34510.710863490545 1
36019.29621417114 1
36047.53740034524 1
36026.267260322 1
36831.82724695755 1
45228.49241068828 1
41973.49441891512 1
16828.21840101669 1
18016.129456529405 1
30355.34657202453 1
21972.13971871468 1
22026.33210296844 1
19184.141997808085 1
28017.00320737886 1
22825.82535933144 1
37983.53712726868 1
36022.58433529089 1
24031.614634312555 1
39979.00316056302 1
43961.78798498724 1
48030.10463638684 1
45973.32374972372 1
52847.84074891772 1
60033.67486093276 1
55954.60863544349 1
31973.45603143833 1
20018.84116542548 1
24020.091090096084 1
39956.13526906775 1
27998.18178773797 1
46010.1962810663 1
57226.73596179053 1
21191.37714911977 1
34398.7589782654 1
30373.92694073473 1
31955.456858525355 1
43003.15769621435 1
36015.79702090197 1
38006.22428509537 1
44782.103709890456 1
51987.09705647251 1
54037.26502272686 1
57986.93402630518 1
29971.860722029047 1
20838.13476663724 1
19966.45996410387 1
23220.41221824488 1
21184.377471013668 1
56038.33880265724 1
48040.80927800393 1
25965.55964033088 1
39970.163848398144 1
23959.108917461283 1
30003.3155164876 1
31221.762735160435 1
31991.0699222577 1
33985.58402146447 1
34046.77867973753 1
39981.906734626216 1
53170.92498293138 1
44004.54438287881 1
50008.63636598119 1
59996.31972175762 1
72004.78205658725 1
61987.359941007 1
71997.57051024995 1
32037.43066536894 1
34050.50101814715 1
37964.6890283941 1
25616.832758480028 1
25188.70111729688 1
17993.236592370242 1
30013.327540416456 1
39965.38779081056 1
36000.88884413259 1
37973.62126131424 1
43998.603453953576 1
45975.63060872456 1
48020.47617963611 1
49951.91415436463 1
51963.22523628078 1
56002.02588447653 1
59986.389112803314 1
64029.0727324866 1
51975.44898399191 1
23958.15410858961 1
28038.975106649275 1
16035.514731295185 1
33982.72434502472 1
34035.10507058127 1
33988.963484475746 1
29977.193636372147 1
29392.372238460663 1
30035.414514829183 1
28010.10823643236 1
28781.6791538234 1
30049.98420740608 1
32005.5153476103 1
38006.93424357368 1
32011.689270221897 1
42022.997823835554 1
52025.52093592653 1
60037.14092392126 1
68002.82951940404 1
71975.52864582073 1
14552.385934015889 1
16372.434567856868 1
29983.12645687211 1
22036.625288675525 1
21985.759252144104 1
30683.13936280592 1
43965.52808941391 1
45954.77140407628 1
47951.33249102657 1
55952.22618949408 1
61487.708445237 1
63982.45001942207 1
64006.03647171161 1
19175.52351169359 1
19966.588390664 1
27659.91315390668 1
26857.21314915956 1
26030.654776553576 1
28041.95176513365 1
25989.07377046185 1
14445.547069554988 1
33791.08306957565 1
15217.85072396099 1
32027.349710581508 1
30034.78179885433 1
25600.23066000655 1
28043.1869690893 1
62415.72364151112 1
53999.98717725816 1
29951.90688689482 1
44019.53470898581 1
31964.55368405639 1
28035.43807854781 1
36100.36645395002 1
33642.32839894616 1
34016.299903511055 1
32008.95714643766 1
33229.1591532926 1
38375.5785689794 1
36044.08739051672 1
20041.64902307104 1
37947.702822447725 1
39977.9767571176 1
41950.91928304869 1
41215.88361033978 1
48002.42438261506 1
44021.0219505981 1
48045.40233383796 1
31964.837151340827 1
30795.9543778466 1
52810.55748669376 1
64281.10106606185 1
75971.85369097203 1
15979.703939547166 1
19168.672698237897 1
21984.67975074938 1
24037.98352858706 1
30837.391300686548 1
35965.75513583788 1
37956.98010923377 1
39976.92453997446 1
46031.45313795721 1
44035.32075510717 1
44848.70884761387 1
59953.789569436274 1
36032.076862441536 1
31487.69407769305 1
31983.941440596347 1
35955.0601469729 1
67953.06368632748 1
59978.58373225416 1
38435.51540440591 1
64005.80626786799 1
31952.14856076861 1
33959.30864723069 1
36003.24149649323 1
37976.62981073115 1
19952.559170048844 1
39972.67713997377 1
36042.60737195257 1
37960.374630629165 1
42032.16154532401 1
42010.09044881151 1
39991.36403456162 1
46038.62930695006 1
43973.97845002735 1
49968.62006064588 1
61471.30347532922 1
55953.59439271585 1
56043.48816790603 1
30007.03535046936 1
29030.51354893759 1
26005.22076545231 1
17964.98818630045 1
32017.42342039051 1
36792.04255590411 1
40024.956264256674 1
38012.0745024919 1
42043.67694930775 1
39991.49624251633 1
34047.57367074375 1
43985.5162584851 1
43176.84157792114 1
44040.77060788803 1
40017.37975836854 1
51979.94402104561 1
48017.83973046369 1
46035.81492917588 1
43994.2889393556 1
43962.48239495071 1
50026.528328476525 1
35976.82099748189 1
33982.1565081366 1
24747.804111121 1
30031.609856090927 1
49994.94335373414 1
55992.541132459286 1
51989.70615888471 1
65950.89337409049 1
72035.64820042759 1
75967.33515678359 1
16023.89291903209 1
20008.097936760987 1
22366.97157901908 1
22757.88727207293 1
21552.830783406087 1
22830.74221413749 1
26898.038244185045 1
26032.845500994263 1
28048.814437611745 1
28774.074807804256 1
32007.893879758587 1
44015.11262523481 1
41958.22851290351 1
52036.13994942124 1
50030.29908947497 1
60025.29778952261 1
60000.40915226686 1
68035.30490617314 1
72022.15500523121 1
23045.38303731762 1
13645.397484919888 1
17965.226910197107 1
20403.469265465345 1
20555.059305799536 1
22425.623299635467 1
11165.49297054454 1
23247.50685282272 1
23960.22571642537 1
22003.4650788431 1
22017.58326874482 1
25216.74685173918 1
23201.78921985233 1
59976.822398469856 1
60015.76577708031 1
44036.9767071952 1
36013.36509671822 1
51995.80251703203 1
47999.02300697525 1
56009.297020499085 1
67958.70191148476 1
68029.46798133934 1
72042.82665252892 1
27957.84392536427 1
38369.42838355113 1
41968.86942427076 1
33222.23219049126 1
18034.692977089 1
35998.47382665374 1
36449.45626037812 1
43977.21366069192 1
42012.12812036538 1
23956.45208102048 1
14955.826921162849 1

From the global schema, we knew that the name is wrong since it should be NumberOfViews. From the output of the code, the data seems to be in float type whereas from the global schema it should be in integer. Therefore the numbers are rounded down and converted to integer

In [22]:
#Renaming the column to NumberOfViews
dataset2 = dataset2.rename(columns={'Views': 'NumberOfViews'})

#Converting number of views to integer and rounding up the number to upper number.
dataset2.NumberOfViews = dataset2.NumberOfViews.round(0).astype('Int64')

Next is the OpeningDate and OpeningTime

# OpeningDate and OpeningTime

First we skim the column with for loop

In [23]:
#Skimming the OpeningDate column
for x,y in dataset2['OpeningDate'].value_counts().to_dict().items():
    print(x,y)

2012-03-04 4
2013-01-23 3
2013-08-29 3
2012-11-23 3
2012-01-25 3
2012-09-02 3
2013-04-26 3
2012-04-15 3
2012-08-22 3
2012-12-01 2
2012-05-09 2
2013-07-25 2
2013-05-11 2
2012-09-12 2
2012-10-06 2
2012-05-26 2
2013-01-03 2
2013-06-26 2
2012-12-13 2
2012-11-12 2
2013-08-10 2
2013-11-29 2
2013-04-21 2
2013-06-10 2
2013-10-28 2
2012-02-13 2
2013-04-07 2
2012-06-11 2
2012-05-30 2
2013-10-02 2
2013-02-24 2
2013-07-09 2
2013-04-01 2
2013-01-25 2
2013-05-22 2
2013-02-28 2
2012-11-06 2
2012-07-18 2
2013-10-24 2
2012-05-11 2
2013-10-25 2
2013-02-10 2
2013-01-05 2
2012-11-27 2
2012-11-17 2
2012-10-14 2
2013-02-02 2
2012-01-31 2
2013-01-06 2
2012-03-14 2
2013-02-11 2
2013-04-02 2
2013-11-17 2
2013-11-13 1
2012-07-06 1
2012-03-07 1
2013-04-14 1
2012-04-06 1
2013-04-08 1
2013-02-09 1
2012-01-12 1
2012-01-04 1
2013-10-06 1
2013-05-14 1
2012-01-30 1
2013-04-09 1
2013-09-18 1
2013-06-14 1
2012-08-08 1
2012-08-17 1
2012-11-16 1
2012-01-14 1
2013-03-31 1
2013-09-16 1
2012-07-29 1
2013-06-09 1
2012-03-29 1
2012-05-31 1
2013-06-28 1
2012-03-24 1
2012-05-19 1
2013-06-02 1
2012-03-21 1
2012-04-01 1
2013-08-05 1
2013-11-15 1
2013-12-20 1
2013-12-17 1
2012-06-28 1
2012-04-23 1
2013-10-01 1
2012-04-28 1
2012-01-20 1
2012-02-11 1
2012-06-25 1
2012-07-22 1
2012-05-04 1
2013-03-29 1
2013-11-07 1
2013-11-02 1
2013-07-06 1
2012-06-14 1
2013-01-29 1
2012-03-31 1
2013-05-15 1
2012-10-29 1
2013-10-29 1
2012-10-13 1
2012-11-05 1
2013-01-02 1
2013-07-30 1
2013-12-16 1
2012-06-21 1
2013-03-19 1
2012-09-11 1
2013-02-16 1
2013-03-17 1
2013-08-22 1
2013-06-23 1
2012-11-24 1
2013-12-29 1
2012-05-01 1
2013-05-31 1
2012-11-11 1
2013-03-26 1
2013-07-14 1
2012-12-28 1
2013-11-25 1
2012-07-14 1
2012-09-13 1
2012-10-01 1
2012-01-24 1
2012-10-30 1
2013-11-30 1
2013-09-08 1
2013-07-18 1
2012-09-03 1
2012-04-21 1
2012-09-27 1
2013-09-11 1
2012-12-27 1
2013-01-26 1
2012-01-15 1
2012-08-03 1
2013-02-26 1
2012-08-06 1
2012-06-10 1
2012-06-15 1
2013-09-29 1
2013-02-07 1
2012-09-16 1
2012-01-22 1
2012-04-26 1
2013-12-21 1
2013-07-03 1
2012-05-29 1
2013-08-24 1
2012-01-02 1
2013-08-02 1
2013-07-26 1
2012-09-06 1
2012-04-24 1
2013-10-13 1
2013-08-12 1
2013-02-05 1
2013-02-03 1
2013-07-29 1
2012-11-02 1
2013-10-10 1
2013-04-22 1
2013-09-12 1
2012-07-24 1
2012-06-13 1
2012-10-22 1
2012-03-18 1
2012-04-19 1
2013-01-13 1
2013-12-25 1
2012-09-28 1
2013-05-10 1
2012-10-15 1
2012-02-22 1
2013-05-16 1
2012-11-15 1
2013-05-25 1
2012-04-10 1
2012-10-21 1
2013-01-15 1
2013-05-23 1
2012-01-01 1
2012-11-01 1
2012-03-22 1
2013-03-09 1
2013-11-26 1
2013-06-21 1
2013-09-13 1
2013-05-18 1
2013-10-03 1
2012-09-01 1
2013-04-19 1
2012-09-05 1
2013-04-18 1
2012-01-13 1
2013-08-18 1
2012-10-17 1
2012-03-09 1
2013-08-09 1
2013-11-24 1
2013-01-21 1
2012-05-22 1
2012-04-20 1
2012-02-02 1
2013-04-16 1
2013-07-17 1
2012-04-05 1
2012-08-25 1
2013-05-21 1
2013-11-18 1
2012-10-10 1
2012-09-22 1
2012-09-07 1
2013-06-20 1
2013-12-18 1
2012-09-30 1
2013-01-17 1
2013-08-21 1
2013-01-28 1
2012-08-10 1
2012-10-03 1
2013-12-12 1
2012-12-05 1
2013-02-08 1
2013-11-04 1
2013-11-01 1
2013-03-16 1
2013-08-08 1
2013-09-23 1
2013-09-21 1
2013-04-10 1
2013-08-07 1
2012-11-04 1
2012-12-14 1
2013-11-08 1
2012-11-07 1
2013-07-08 1
2013-07-20 1
2013-11-05 1
2012-03-23 1
2012-06-24 1
2012-01-26 1
2013-07-21 1
2012-01-08 1
2013-12-02 1
2012-12-12 1
2013-05-09 1
2012-08-18 1
2012-08-14 1
2013-09-27 1
2012-04-17 1
2013-02-12 1
2013-12-09 1
2012-10-05 1
2013-03-24 1
2013-12-10 1
2012-01-17 1
2013-08-27 1
2013-12-03 1
2013-02-22 1
2012-07-09 1
2013-08-23 1
2012-02-18 1

In [24]:
#Skimming the OpeningTime column
for x,y in dataset2['OpeningTime'].value_counts().to_dict().items():
    print(x,y)

15:00:00 116
12:00:00 115
00:00:00 103

Few problems, from the global schema opening date and opening time are combined into one column of OpenDate. The format for it is dateThour and it's in string format. Therefore, both column are combined into one OpenDate column with T in the middle. Then the former 2 columns are dropped

In [25]:
#combining opening date and opening time to opendate
dataset2['OpenDate'] = dataset2['OpeningDate'].str.split('-', expand=False).str[0:3].apply(''. join) + 'T' + dataset2['OpeningTime'].str.split(':', expand=False).str[0:3].apply(''. join)

#dropping the OpeningTime and OpeningDate column
dataset2 = dataset2.drop(columns=['OpeningTime', 'OpeningDate'])

Next is the ClosingTime and ClosingDate

# ClosingTime and ClosingDate

First we skim the column with for loop

In [26]:
#Skimming the ClosingDate column
for x,y in dataset2['ClosingDate'].value_counts().to_dict().items():
    print(x,y)

2013-03-12 3
2012-09-16 3
2013-09-12 3
2013-08-09 3
2013-12-17 2
2012-09-17 2
2012-04-24 2
2013-09-23 2
2012-06-14 2
2013-01-12 2
2013-04-06 2
2014-01-01 2
2012-06-28 2
2013-07-20 2
2013-10-24 2
2012-05-13 2
2013-06-21 2
2012-07-25 2
2012-05-17 2
2013-11-01 2
2013-03-24 2
2012-05-03 2
2013-02-22 2
2012-05-06 2
2013-07-09 2
2013-03-28 2
2012-11-12 2
2012-11-04 2
2012-12-05 2
2012-12-12 2
2013-07-01 2
2013-04-03 2
2013-05-26 2
2013-03-13 2
2013-06-08 2
2012-06-29 2
2013-01-26 2
2012-04-13 2
2012-04-03 2
2012-12-06 2
2013-12-02 2
2013-11-27 2
2013-11-20 2
2013-03-30 2
2013-08-23 2
2014-01-23 2
2013-11-12 2
2012-04-30 2
2013-05-25 2
2012-10-12 2
2012-10-21 2
2013-12-26 2
2012-12-31 2
2013-01-16 2
2012-11-13 2
2013-09-28 2
2014-02-15 1
2013-04-10 1
2012-09-04 1
2013-06-07 1
2012-12-16 1
2012-03-04 1
2012-02-11 1
2013-04-28 1
2013-05-28 1
2013-02-08 1
2012-09-20 1
2012-09-07 1
2013-05-30 1
2012-08-27 1
2013-10-04 1
2012-04-28 1
2014-01-12 1
2012-05-23 1
2014-01-14 1
2012-07-14 1
2012-06-19 1
2013-08-31 1
2012-06-22 1
2013-02-21 1
2014-02-18 1
2013-07-26 1
2012-03-30 1
2014-01-28 1
2013-10-31 1
2013-10-16 1
2012-07-27 1
2012-04-19 1
2012-04-11 1
2013-07-12 1
2012-08-29 1
2012-08-17 1
2013-08-12 1
2013-05-07 1
2012-04-15 1
2012-09-27 1
2014-01-16 1
2013-12-05 1
2013-12-07 1
2013-02-01 1
2013-05-21 1
2013-02-28 1
2012-05-30 1
2013-07-14 1
2012-12-28 1
2013-02-24 1
2013-08-08 1
2013-09-07 1
2014-01-27 1
2012-12-23 1
2013-06-25 1
2012-11-01 1
2014-01-15 1
2012-09-12 1
2012-09-19 1
2013-04-02 1
2013-03-06 1
2012-11-10 1
2013-04-17 1
2013-05-16 1
2013-07-23 1
2014-03-29 1
2013-12-24 1
2012-06-30 1
2013-08-29 1
2012-11-25 1
2014-02-23 1
2012-09-02 1
2012-11-30 1
2012-01-29 1
2012-04-23 1
2013-05-01 1
2013-12-30 1
2013-10-08 1
2013-09-16 1
2012-08-02 1
2012-05-21 1
2012-10-27 1
2013-10-11 1
2013-10-01 1
2013-04-26 1
2013-01-22 1
2012-03-14 1
2013-09-01 1
2013-05-31 1
2012-09-08 1
2012-07-15 1
2013-10-29 1
2013-09-24 1
2013-04-08 1
2012-11-15 1
2012-11-05 1
2012-03-22 1
2013-09-09 1
2014-02-19 1
2013-06-06 1
2013-11-22 1
2014-03-12 1
2012-11-23 1
2013-02-12 1
2013-08-28 1
2013-12-29 1
2012-12-02 1
2013-11-11 1
2012-08-23 1
2012-02-08 1
2012-08-12 1
2012-08-10 1
2013-01-20 1
2013-04-25 1
2012-07-18 1
2012-08-09 1
2013-12-27 1
2013-01-13 1
2014-01-24 1
2012-11-27 1
2013-10-09 1
2012-11-14 1
2012-03-07 1
2012-06-25 1
2013-06-15 1
2012-12-15 1
2013-03-01 1
2013-10-15 1
2012-06-04 1
2013-06-20 1
2013-03-05 1
2013-02-06 1
2013-09-11 1
2012-07-08 1
2012-01-31 1
2012-04-21 1
2013-05-08 1
2013-09-19 1
2013-08-16 1
2012-02-24 1
2012-10-31 1
2013-06-18 1
2013-06-22 1
2012-12-04 1
2012-03-13 1
2013-11-16 1
2013-01-15 1
2012-04-08 1
2013-04-21 1
2012-06-10 1
2012-06-21 1
2012-05-20 1
2012-04-02 1
2013-07-15 1
2013-07-17 1
2013-03-16 1
2012-11-20 1
2012-10-06 1
2012-05-24 1
2014-01-04 1
2012-09-09 1
2012-06-08 1
2012-10-07 1
2014-02-16 1
2012-10-30 1
2013-01-31 1
2013-10-20 1
2012-09-05 1
2013-02-27 1
2012-08-01 1
2012-10-09 1
2012-04-01 1
2012-11-02 1
2013-01-04 1
2013-02-05 1
2013-03-04 1
2013-04-09 1
2013-12-04 1
2013-02-25 1
2013-04-05 1
2014-01-30 1
2013-06-14 1
2013-11-06 1
2013-10-23 1
2013-05-10 1
2012-08-24 1
2013-11-05 1
2013-01-03 1
2013-08-19 1
2012-11-21 1
2012-04-22 1
2012-11-09 1
2012-07-24 1
2012-04-25 1
2013-08-04 1
2013-08-20 1
2012-02-07 1
2013-12-23 1
2013-04-12 1
2012-09-13 1
2013-09-18 1
2013-05-13 1
2014-01-08 1
2013-02-02 1
2013-06-10 1
2014-01-22 1
2013-05-23 1
2014-02-08 1
2012-03-17 1
2013-11-25 1
2014-02-01 1
2012-07-23 1
2013-09-22 1
2013-09-06 1
2012-12-07 1
2013-12-08 1
2012-10-02 1
2012-03-03 1

In [27]:
#Skimming the OpeningTime column
for x,y in dataset2['ClosingTime'].value_counts().to_dict().items():
    print(x,y)

15:00:00 116
12:00:00 115
00:00:00 103

Few problems, from the global schema closing date and Closing time are combined into one column of CloseDate. The format for it is dateThour and it's in string format. Therefore, both column are combined into one CloseDate column with T in the middle. Then the former 2 columns are dropped

In [28]:
#combining closing date and closing time to closedate
dataset2['CloseDate'] = dataset2['ClosingDate'].str.split('-', expand=False).str[0:3].apply(''. join) + 'T' + dataset2['ClosingTime'].str.split(':', expand=False).str[0:3].apply(''. join)

#dropping the OpeningTime and OpeningDate column
dataset2 = dataset2.drop(columns=['ClosingDate', 'ClosingTime'])

It's done, next we're checking if there's any problem

In [29]:
dataset2.info()
dataset2.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 334 entries, 0 to 333
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             334 non-null    int64
 1   Title          334 non-null    object
 2   Company        334 non-null    object
 3   Location       334 non-null    object
 4   Category       334 non-null    object
 5   Salary         334 non-null    float64
 6   ContractType   334 non-null    object
 7   ContractTime   334 non-null    object
 8   NumberOfViews  334 non-null    Int64
 9   OpenDate       334 non-null    object
 10  CloseDate      334 non-null    object
dtypes: Int64(1), float64(1), int64(1), object(8)
memory usage: 29.2+ KB

,Id,Title,Company,Location,Category,Salary,ContractType,ContractTime,NumberOfViews,OpenDate,CloseDate
0,72705505,AVIATION LOANS ADMINISTRATION,CER FINANCIAL,LONDON,ACCOUNTING & FINANCE JOBS,33600.0,non-specified,contract,26899,20131006T000000,20131205T000000
1,72705506,"PAYROLL ANALYST CITY UPTO **** , ****",LMA RECRUITMENT LTD,LONDON,ACCOUNTING & FINANCE JOBS,35004.0,non-specified,permanent,27998,20121003T120000,20121102T120000
2,72705507,INVESTMENT TEAM ASSISTANT FOR LEADING PRIVATE ...,AUSTIN ANDREW LTD,LONDON,ACCOUNTING & FINANCE JOBS,45000.0,non-specified,permanent,35955,20120101T000000,20120131T000000
3,72705508,SWAPS COLLATERAL CONTROL OFFICER,BRIAN DURHAM RECRUITMENT SERVICES LTD,CITY,ACCOUNTING & FINANCE JOBS,39996.0,non-specified,permanent,31984,20121014T000000,20121113T000000
4,72705509,LOANS ADMINISTRATION TEMP,CER FINANCIAL,LONDON,ACCOUNTING & FINANCE JOBS,39360.0,non-specified,contract,31488,20121117T120000,20130116T120000

# SourceName

The source name column is actually missing from the second dataset. The problem is that we can't really deduct where the source of each job offer came from. Therefore it's left as missing values for the SourceName column. When the dataset are both merged, it will automatically update for dataset2 and input it as missing values

Finally both dataset from task 1 and dataset2 are merged together

# Merging

Merging both dataset together

In [30]:
#Function to merge both dataset1 and dataset 2 into one dataset
merge = pd.concat([dataset1,dataset2], axis=0)

#Checking if the new dataset has both dataset
merge.info()
merge.tail(10)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 55499 entries, 0 to 333
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             55499 non-null  int64
 1   Title          55499 non-null  object
 2   Location       55499 non-null  object
 3   Company        55499 non-null  object
 4   ContractType   55499 non-null  object
 5   ContractTime   55499 non-null  object
 6   Category       55499 non-null  object
 7   Salary         55499 non-null  float64
 8   OpenDate       55499 non-null  object
 9   CloseDate      55499 non-null  object
 10  SourceName     55165 non-null  object
 11  NumberOfViews  55499 non-null  Int64
dtypes: Int64(1), float64(1), int64(1), object(9)
memory usage: 5.6+ MB

,Id,Title,Location,Company,ContractType,ContractTime,Category,Salary,OpenDate,CloseDate,SourceName,NumberOfViews
324,72705829,CAPITAL MARKETS MANAGEMENT ACCOUNTANT,LONDON,ALBANY BECK CONSULTING LTD,non-specified,permanent,ACCOUNTING & FINANCE JOBS,54996.0,20121117T150000,20130116T150000,NaN,44005
325,72705830,COVERED BONDS CREDIT ANALYST,LONDON,RANDSTAD FINANCIAL PROFESSIONAL LTD,non-specified,permanent,ACCOUNTING & FINANCE JOBS,66504.0,20131229T150000,20140329T150000,NaN,53171
326,72705831,SENIOR BUSINESS BANKING RELATIONSHIP MANAGER E...,NORTH LONDON,THE OAKLAND PARTNERSHIP LTD,non-specified,permanent,ACCOUNTING & FINANCE JOBS,50004.0,20130210T120000,20130312T120000,NaN,39982
327,72705832,LOANS ANALYST,LONDON,BLAYNEY PERSONNEL LTD,non-specified,permanent,ACCOUNTING & FINANCE JOBS,42504.0,20131025T120000,20131224T120000,NaN,34047
328,72705833,NEWLY QUALIFIED ASSOCIATE,LONDON,REED FINANCE,non-specified,permanent,ACCOUNTING & FINANCE JOBS,42504.0,20120501T150000,20120630T150000,NaN,33986
329,72705834,FINANCIAL CONTROL OFFICER REGULATORY REPORTING,THE CITY,HAYS FINANCIAL MARKETS,non-specified,permanent,ACCOUNTING & FINANCE JOBS,39996.0,20130531T000000,20130829T000000,NaN,31991
330,72705835,MANAGEMENT ACCOUNTANT LONDON,THE CITY,MORGAN MCKINLEY GROUP LTD,non-specified,contract,ACCOUNTING & FINANCE JOBS,39000.0,20121111T120000,20121125T120000,NaN,31222
331,72705836,RISK MANAGER FSA / REGULATORY FRAMEWORKS,BATH,INCITE SOLUTIONS LTD,non-specified,permanent,ACCOUNTING & FINANCE JOBS,37500.0,20130326T150000,20130525T150000,NaN,30003
332,72705837,RELATIONSHIP / SALES EXECUTIVE MULTILINGUAL,LONDON,C.K.R. RECRUITMENT LTD,non-specified,permanent,"PR, ADVERTISING & MARKETING JOBS",30000.0,20130714T150000,20130912T150000,NaN,23959
333,72705838,CORPORATE TAX COMPLIANCE CLIENT SERVICE ADMINI...,UK,RANDSTAD FINANCIAL PROFESSIONAL LTD,non-specified,contract,ACCOUNTING & FINANCE JOBS,18720.0,20120218T150000,20120303T150000,NaN,14956

Looks like both dataset are merged successfuly, the first dataset has 55165 data after deleting duplicates and second dataset has 334 data. Adding both of them together we got 55499 except for the SourceName since the second dataset SourceName is left as NaN. We can also see the NaN values for the second dataset that we mentioned before that should be left as missing values. Next we need to check if the merging resulted in data conflicts

# DUPLICATES

There's a possibility that there are data conflicts in form of duplicates therefore we should check the combined dataframe again for duplicates. Like in task 1, we use 3 columns to search for duplicates which are Title, Location, and Category.

- Title is choosen because it's more likely that the name could be the same
- OpenDate and CloseDate is choosen because if the duplicated rows has the same name and has the same OpenDate and CloseDate with each other,
it's more likely that it's a duplication

In [31]:
#Checking the merged dataset for duplicates based by Title, OpenDate, and CloseDate
merge[merge.duplicated(['Title', 'OpenDate', 'CloseDate'], keep=False)].sort_values(['Title'])

,Id,Title,Location,Company,ContractType,ContractTime,Category,Salary,OpenDate,CloseDate,SourceName,NumberOfViews
22758,68840315,ACCOUNTS PAYABLE / COMPLIANCE / ADMINISTRATOR,LONDON,PRIME PERSONNEL SERVICES LTD,non_specified,permanent,ACCOUNTING & FINANCE JOBS,28500.0,20130106T000000,20130205T000000,jobs.catererandhotelkeeper.com,31851
155,72705660,ACCOUNTS PAYABLE / COMPLIANCE / ADMINISTRATOR,LONDON,PRIME PERSONNEL SERVICES LTD,non-specified,permanent,ACCOUNTING & FINANCE JOBS,28500.0,20130106T000000,20130205T000000,NaN,22758
6331,66894092,ADVANCED DATA ANALYTIC MANAGERS,THE CITY,OLIVER JAMES ASSOCIATES LTD,non_specified,permanent,IT JOBS,57500.0,20130106T120000,20130406T120000,staffnurse.com,34793
195,72705700,ADVANCED DATA ANALYTIC MANAGERS,THE CITY,OLIVER JAMES ASSOCIATES LTD,non-specified,permanent,IT JOBS,57504.0,20130106T120000,20130406T120000,NaN,45973
12470,68218723,ASSISTANT ACCOUNTANT FINANCIAL SERVICES EXPERI...,LONDON,MALDON PARTNERS LTD,non_specified,permanent,ACCOUNTING & FINANCE JOBS,27500.0,20131105T000000,20140104T000000,cwjobs.co.uk,31851
...,...,...,...,...,...,...,...,...,...,...,...,...
2420,62008199,SUPPORT ANALYST FRONT OFFICE,LONDON,NEWSIDE CONSULTING LTD,non_specified,permanent,ACCOUNTING & FINANCE JOBS,56000.0,20130309T120000,20130508T120000,careworx.co.uk,31851
53335,72460519,TRADE FINANCE OFFICER,LONDON,CER FINANCIAL,non_specified,contract,ACCOUNTING & FINANCE JOBS,46000.0,20120930T000000,20121030T000000,jobs.guardian.co.uk,31851
142,72705647,TRADE FINANCE OFFICER,LONDON,CER FINANCIAL,non-specified,contract,ACCOUNTING & FINANCE JOBS,45996.0,20120930T000000,20121030T000000,NaN,36792
28262,69266259,TRADE STRUCTURED FINANCE MANAGER COMMODITY TRADER,LONDON,LMA RECRUITMENT LTD,non_specified,permanent,ACCOUNTING & FINANCE JOBS,72500.0,20131117T120000,20140215T120000,cv-library.co.uk,31851
185,72705690,TRADE STRUCTURED FINANCE MANAGER COMMODITY TRADER,LONDON,LMA RECRUITMENT LTD,non-specified,permanent,ACCOUNTING & FINANCE JOBS,72504.0,20131117T120000,20140215T120000,NaN,58040

As we can see from the ouptut, there are a lot of duplicates in the merged dataset. I'm assuming that the data from the first dataset is the actual data and the data from the second dataset is the duplicates therefore, the second data is dropped.

In [32]:
#Code to drop the duplicates while keeping the first one
merge = merge.drop_duplicates(subset=['Title', 'OpenDate', 'CloseDate'], keep='first')

## The Global Key
Write down the identified global key:

As mentioned in the duplicates section, we use 3 columns to identify the duplicates therefore the Global Key are

**| Title  | OpenDate | CloseDate  |**

## Saving data
Save the integrated data

In [33]:
# code to save output data
merge.to_csv("dataset_integrated.csv",index = False)

## Summary
Give a short summary and anything you would like to talk about assessment 2 part 2 here.

For the task 2, the dataset is checked with the global schema and dataset 1 then the schema and data conflict is resolved. After that both dataset is merged, then checked again for duplicates. After duplicates are deleted then it's saved into dataset_integrated.csv